# allowBuilds:
#   esbuild: set this to true or false
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: false
  msgpackr-extract: true
  prisma: true
  workerd: true
