# generated by datamodel-codegen:
#   filename:  ScoreResult.json
#   timestamp: 2026-09-20T14:58:20+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, confloat, conint


class ScorerKind(Enum):
    deterministic = 'deterministic'
    programmatic = 'programmatic'
    llm_judge = 'llm_judge'


class Model(BaseModel):
    trajectoryId: str
    scorerKey: str
    scorerKind: ScorerKind
    value: confloat(ge=0.0, le=1.0)
    passed: bool
    confidence: confloat(ge=0.0, le=1.0)
    rationale: str | None
    costUsd: float | None = 0
    latencyMs: conint(ge=-9007199254740991, le=9007199254740991) | None = 0
